const series = [
  {
    id: 1,
    Title: "Kabiyesi",
    Year: 2025,
    Type: "Series",
    Country: "Nigeria",
    Language: "Yoruba",
    Genre: "Drama",
    Stars: "Annetta Adebusuyi, Patrick Diabuah, Akin Lewis",
    Total_Seasons: 1,
    Status: "ongoing",
    Subtitle: "English",
    img: "kabiyesi.jpg",
    rating: 4.5,
    plot: "An epic story of betrayal, honour and duty. When Princess Aderiyife’s wedding day is marred by tragedy, she questions her destiny. Can she pick up the pieces to become the ruler her kingdom deserves?",
  },
  {
    id: 2,
    Title: "Cheta’m",
    Year: 2025,
    Type: "Series",
    Country: "Nigeria",
    Language: "Igbo",
    Genre: "Drama",
    Stars: "Kingsley Nwachukwu, Oluchi Amajudyi, Kalu Ikeagwu",
    Total_Seasons: 2,
    Status: "ongoing",
    Subtitle: "English",
    img: "chetam.jpg",
    rating: 4.5,
    plot: "A love story that transcends boundaries. A young teenage couple, who found a once in a lifetime kind of love, have to fight against all odds to stay together.",
  },
  {
    id: 3,
    Title: "My Siblings and I",
    Year: 2018,
    Type: "Series",
    Country: "Nigeria",
    Language: "English",
    Genre: "Comedy",
    Stars:
      "Moyo Farawe Ahmed, Funke Akindele, And, Somadina Anyama, Raymond Asuquo, Patrick Doyle, Cynthia Ebijie, Chinelo Ejianwu, Babaseun Faseru, Bofie Itombra",
    Total_Seasons: 4,
    Status: "Complete",
    Subtitle: "English",
    img: "siblings.jpg",
    rating: 4.5,
    plot: "Follow the hilarious antics and heated conflicts of the Aberuagbas, as they experience the ups and downs of family life.",
  },
  {
    id: 4,
    Title: "Wura",
    Year: 2023,
    Type: "Series",
    Country: "Nigeria",
    Language: "English",
    Genre: "Drama",
    Stars:
      "Scarlet Gomez, Yomi Fash-Lanso, Ray Adeka, Martha Ehinome, Iremide Adeoye, Adediwura Lanre, Ego Iheanacho, Modesinuola Ogundiwin, Carol King, Mofe Stephen",
    Total_Seasons: 3,
    Status: "ongoing",
    Subtitle: "English",
    img: "wura.jpeg",
    rating: 4.5,
    plot: "All roads lead to Iperindo as the town prepares for the wedding of Tumi and Jeje, but is this the start of a fairytale forever, or the end of a dream?",
  },
  {
    id: 5,
    Title: "Between Worlds",
    Year: 2025,
    Type: "Series",
    Country: "Nigeria",
    Language: "English",
    Genre: "Drama",
    Stars: "Femi Branch, Ropo Ewenla, Awe Ayobami",
    Total_Seasons: 1,
    Status: "ongoing",
    Subtitle: "English",
    img: "Between-Worlds.jpg",
    rating: 4.5,
    plot: "A cyber-criminal who scams a widow of her life savings is banished to the realm of the past when the widow demands justice from the gods. Barely alive, he becomes a slave in the past.",
  },
  {
    id: 6,
    Title: "Alex From Oil And Gas",
    Year: 2025,
    Type: "Series",
    Country: "Nigeria",
    Language: "English",
    Genre: "Drama",
    Stars: "Detola Jones, Scarlet Gomez",
    Total_Seasons: 1,
    Status: "ongoing",
    Subtitle: "English",
    img: "alex.jpeg",
    rating: 4.5,
    plot: "A no-nonsense career woman/social media influencer is only to be swept off her feet by a charming stranger who turns out to be much closer, and more complicated, than she ever imagined.",
  },
];

const home = [
  { id: 1, name: "Kabiyesi", rating: 4.5, plot: "t", seasons: 1 },
  { id: 1, name: "Kabiyesi", rating: 4.5, plot: "t", seasons: 1 },
];

module.export = { series, home };
